/* ─────────────────────────────────────────────────────
   SageHealth — Doctor Report PDF Generator
   Pure Node.js using PDFKit — no Python needed
   ───────────────────────────────────────────────────── */

const PDFDocument = require('pdfkit');

exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method not allowed' };
  }

  let body;
  try { body = JSON.parse(event.body); }
  catch (e) { return { statusCode: 400, body: JSON.stringify({ error: 'Invalid JSON' }) }; }

  const { stateMap, profile, signals, commitments, reportDate, doctorInfo } = body;
  const date = reportDate || new Date().toISOString().slice(0, 10);

  // ── Step 1: Generate clinical narrative via Groq ──
  const groqKey = process.env.GROQ_API_KEY;
  let narrative = 'Clinical narrative not available.';

  if (groqKey) {
    try {
      const prompt = buildClinicalPrompt(stateMap, profile, signals, commitments, doctorInfo);
      const res = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${groqKey}`
        },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile',
          max_tokens: 600,
          temperature: 0.3,
          messages: [
            { role: 'system', content: 'You are a clinical documentation assistant. Write concise, precise clinical summaries for physician review. Use medical terminology. Never diagnose — only report patterns and observations.' },
            { role: 'user', content: prompt }
          ]
        })
      });
      const data = await res.json();
      narrative = data.choices?.[0]?.message?.content || narrative;
    } catch(e) {
      console.log('Groq narrative failed:', e.message);
    }
  }

  // ── Step 2: Generate PDF using PDFKit ──
  try {
    const pdfBuffer = await generatePDF(stateMap, profile, signals, commitments, narrative, date);
    const base64 = pdfBuffer.toString('base64');

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="myDrSage_Report_${date}.pdf"`,
        'Cache-Control': 'no-cache'
      },
      body: base64,
      isBase64Encoded: true
    };
  } catch(e) {
    console.log('PDF error:', e.message);
    return { statusCode: 500, body: JSON.stringify({ error: e.message }) };
  }
};

// ── PDF GENERATION ────────────────────────────────────
function generatePDF(stateMap, profile, signals, commitments, narrative, date) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'LETTER', margin: 50 });

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const m  = stateMap || {};
    const c  = m.cardio || {};
    const s  = m.sleep || {};
    const t  = m.temperature || {};
    const a  = m.activity || {};
    const r  = m.recovery || {};
    const p  = profile || {};
    const W  = doc.page.width - 100; // usable width

    // Colors
    const BLUE  = '#1D6FA4';
    const GREEN = '#0E9F6E';
    const AMBER = '#B45309';
    const RED   = '#C0392B';
    const GREY  = '#6B7F96';
    const DARK  = '#1A2535';

    // ── HEADER ────────────────────────────────────────
    doc.rect(50, 50, W, 60).fill(BLUE);
    doc.fill('white').fontSize(18).font('Helvetica-Bold')
       .text('myDrSage', 60, 62);
    doc.fontSize(9).font('Helvetica')
       .text('Continuous Biometric Monitoring', 60, 84);
    doc.fontSize(14).font('Helvetica-Bold')
       .text('PATIENT HEALTH REPORT', 200, 62, { width: W - 160, align: 'center' });
    doc.fontSize(9).font('Helvetica')
       .text('For Physician Review', 200, 84, { width: W - 160, align: 'center' });
    doc.fontSize(9)
       .text(`Date: ${date}`, 60, 62, { width: W, align: 'right' })
       .text('Generated by myDrSage AI', 60, 76, { width: W, align: 'right' });

    doc.fill(DARK);
    let y = 125;

    // ── PATIENT INFO ─────────────────────────────────
    doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 8;
    doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text('PATIENT INFORMATION', 50, y); y += 16;

    const infoItems = [
      ['Patient', p.name || 'Not provided'],
      ['Age / Sex', `${p.age || '--'}yo / ${p.sex || '--'}`],
      ['Conditions', p.conditions || 'None reported'],
      ['Medications', p.medications || 'None reported'],
      ['Ring Device', 'myDrSage V80 Smart Ring'],
      ['Health Grade', m.health_grade || 'B'],
      ['Data Period', '7-day analysis'],
      ['Report Date', date],
    ];

    const colW = W / 2 - 10;
    infoItems.forEach((item, i) => {
      const x = i % 2 === 0 ? 50 : 50 + colW + 20;
      const rowY = y + Math.floor(i / 2) * 18;
      doc.fontSize(8).font('Helvetica-Bold').fill(BLUE).text(item[0] + ':', x, rowY, { width: 90 });
      doc.font('Helvetica').fill(DARK).text(item[1], x + 95, rowY, { width: colW - 95 });
    });
    y += Math.ceil(infoItems.length / 2) * 18 + 12;

    // ── CLINICAL SUMMARY ──────────────────────────────
    doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 8;
    doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text('CLINICAL SUMMARY', 50, y); y += 14;

    doc.fontSize(9).font('Helvetica').fill(DARK);
    const cleanNarrative = narrative.replace(/\*\*/g, '').replace(/\*/g, '').trim();
    const narHeight = doc.heightOfString(cleanNarrative, { width: W, lineGap: 2 });
    doc.text(cleanNarrative, 50, y, { width: W, lineGap: 2 });
    y += narHeight + 16;

    // ── BIOMETRIC DASHBOARD ───────────────────────────
    doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 8;
    doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text('7-DAY BIOMETRIC SUMMARY', 50, y); y += 14;

    // Table header
    const cols = [180, 80, 80, 100, W - 460];
    const headers = ['Metric', 'Value', 'Status', '7-Day Trend', 'Clinical Note'];
    doc.rect(50, y, W, 16).fill('#1D6FA4');
    let x = 50;
    headers.forEach((h, i) => {
      doc.fontSize(8).font('Helvetica-Bold').fill('white').text(h, x + 3, y + 4, { width: cols[i] });
      x += cols[i];
    });
    y += 16;

    function statusColor(status) {
      if (!status) return GREY;
      if (['excellent','optimal','athletic','peak','goal_met'].includes(status)) return GREEN;
      if (['healthy','normal','good','close'].includes(status)) return BLUE;
      if (['elevated','below_norm','watch','moderate','below_goal'].includes(status)) return AMBER;
      return RED;
    }

    const metrics = [
      ['Heart Rate Variability (HRV)', `${c.hrv?.current || '--'} ms`, c.hrv?.status, c.hrv?.trend?.label, `Age norm ~${c.hrv?.age_norm || '--'}ms`],
      ['Resting Heart Rate', `${c.rhr?.current || '--'} BPM`, c.rhr?.status, c.rhr?.trend?.label, ''],
      ['Blood Pressure (avg)', `${c.bp?.systolic || '--'}/${c.bp?.diastolic || '--'} mmHg`, c.bp?.status, c.bp?.trend?.label, `${c.bp?.days_elevated || 0}/7 days elevated`],
      ['Blood Oxygen (SpO₂)', `${c.spo2?.current || '--'}%`, c.spo2?.status, c.spo2?.trend?.label, 'Overnight avg'],
      ['Total Sleep', `${s.total?.avg7d || '--'} h avg`, s.total?.avg7d >= 7 ? 'normal' : 'watch', s.total?.trend?.label, `Goal: ${s.total?.goal || 7.5}h`],
      ['Deep Sleep', `${s.deep?.avg7d || '--'} h avg`, s.deep?.avg7d >= 1.2 ? 'normal' : 'watch', s.deep?.trend?.label, 'Target 1.5h'],
      ['REM Sleep', `${s.rem?.avg7d || '--'} h avg`, s.rem?.avg7d >= 1.2 ? 'normal' : 'watch', s.rem?.trend?.label, 'Target 1.5h'],
      ['Skin Temperature', `${t.last_night_f || '--'}°F`, t.status?.replace('_',' '), t.trend?.label, `${t.deviation_f > 0 ? '+' : ''}${t.deviation_f || 0}°F from baseline`],
      ['Daily Steps', `${(a.steps_avg7d || 0).toLocaleString()}/day`, a.status, a.trend?.label, `${a.goal_pct || 0}% of goal`],
      ['Readiness Score', `${r.readiness || '--'}/100`, r.status, r.trend?.label, `${r.consecutive_low_days || 0} consecutive low days`],
    ];

    metrics.forEach((row, idx) => {
      const rowColor = idx % 2 === 0 ? 'white' : '#F7FAFC';
      doc.rect(50, y, W, 15).fill(rowColor);
      let rx = 50;
      row.forEach((cell, ci) => {
        const cellColor = ci === 2 ? statusColor(cell) : DARK;
        doc.fontSize(8).font(ci === 0 ? 'Helvetica-Bold' : 'Helvetica').fill(cellColor)
           .text(cell || '--', rx + 3, y + 3, { width: cols[ci] - 6, lineBreak: false });
        rx += cols[ci];
      });
      y += 15;
    });
    y += 12;

    // ── DETECTED PATTERNS ─────────────────────────────
    const activeSignals = signals || [];
    if (activeSignals.length > 0) {
      if (y > doc.page.height - 200) { doc.addPage(); y = 50; }
      doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 8;
      doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text('DETECTED PATTERNS (for clinical review)', 50, y); y += 10;
      doc.fontSize(8).font('Helvetica').fill(GREY)
         .text('Active patterns flagged by patient for this visit. Observational findings only — not diagnoses. For physician discussion.', 50, y, { width: W }); y += 14;

      activeSignals.forEach(sig => {
        const lvlColor = sig.level === 'urgent' ? RED : sig.level === 'watch' ? AMBER : BLUE;
        const lvlBg = sig.level === 'urgent' ? '#FFF5F5' : sig.level === 'watch' ? '#FFFBEB' : '#E8F4FD';
        doc.rect(50, y, W, 20).fill(lvlBg);
        doc.rect(50, y, 4, 20).fill(lvlColor);
        doc.fontSize(8).font('Helvetica-Bold').fill(lvlColor)
           .text(sig.level?.toUpperCase() || 'INFO', 60, y + 6, { width: 50 });
        doc.font('Helvetica').fill(DARK)
           .text(sig.title || '', 115, y + 6, { width: W - 70 });
        y += 22;
      });
      y += 8;
    }

    // ── COMMITMENTS ───────────────────────────────────
    const activeCommitments = (commitments || []).filter(c => c.status === 'active');
    if (activeCommitments.length > 0) {
      if (y > doc.page.height - 150) { doc.addPage(); y = 50; }
      doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 8;
      doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text('PATIENT HEALTH COMMITMENTS', 50, y); y += 10;
      doc.fontSize(8).font('Helvetica').fill(GREY)
         .text('Commitments made during voice consultations with Dr. Sage. Tracked via biometric data.', 50, y, { width: W }); y += 14;

      activeCommitments.forEach((com, i) => {
        doc.fontSize(9).font('Helvetica').fill(DARK)
           .text(`${i + 1}.  ${com.commitment}`, 50, y, { width: W });
        y += 16;
      });
      y += 8;
    }

    // ── PHYSICIAN NOTES ───────────────────────────────
    if (y > doc.page.height - 150) { doc.addPage(); y = 50; }
    doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 8;
    doc.fontSize(10).font('Helvetica-Bold').fill(BLUE).text('PHYSICIAN NOTES', 50, y); y += 14;

    for (let i = 0; i < 6; i++) {
      doc.rect(50, y, W, 22).fill('#F7FAFC').stroke('#E2E8F0');
      y += 24;
    }
    y += 8;

    // ── FOOTER ────────────────────────────────────────
    doc.rect(50, y, W, 1).fill('#E2E8F0'); y += 6;
    doc.fontSize(7).font('Helvetica').fill(GREY)
       .text(
         'myDrSage is a biometric monitoring and health concierge service. This report is for informational purposes only and does not constitute medical advice, diagnosis, or treatment. ' +
         'All findings should be reviewed by a licensed healthcare provider. Device: myDrSage V80 Smart Ring. Report generated: ' + date + '.',
         50, y, { width: W, align: 'center', lineGap: 2 }
       );

    doc.end();
  });
}

// ── CLINICAL PROMPT ───────────────────────────────────
function buildClinicalPrompt(stateMap, profile, signals, commitments, doctorInfo) {
  const m = stateMap || {};
  const c = m.cardio || {};
  const s = m.sleep || {};
  const t = m.temperature || {};
  const a = m.activity || {};
  const p = profile || {};
  const activeSignals = (signals || []).map(s => `${s.title} [${s.level}]`).join(', ') || 'None';
  const activeCommitments = (commitments || []).filter(c => c.status === 'active').map(c => c.commitment).join('; ') || 'None';

  const hasSignals = activeSignals && activeSignals !== 'None';

  const drLabel = doctorInfo?.label || 'Physician';
  const drId = doctorInfo?.id || 'primary_care';

  // Specialist-specific focus instructions
  const specialistFocus = {
    cardiologist:    'Focus heavily on cardiovascular metrics: HRV, RHR, BP, SpO₂, rhythm patterns. Use cardiology terminology. Highlight any cardiac signals.',
    endocrinologist: 'Focus on temperature patterns, metabolic signals, HRV as autonomic indicator, sleep patterns. Highlight any thyroid, glucose, or hormonal patterns.',
    pulmonologist:   'Focus on SpO₂, breathing disruptions during sleep, apnea events, REM sleep quality. Highlight any respiratory signals.',
    neurologist:     'Focus on HRV as autonomic nervous system indicator, stress patterns, sleep architecture, recovery metrics. Highlight burnout or nervous system signals.',
    gynecologist:    'Focus on temperature patterns, hormonal cycle signals, HRV variability patterns. Highlight any ovulation or hormonal signals.',
    primary_care:    'Provide a comprehensive overview of all biometric systems. Balance breadth and depth.',
    other:           'Provide a comprehensive overview suitable for any specialist to quickly understand this patients biometric picture.',
  }[drId] || 'Provide a comprehensive clinical overview.';

  return \`Generate a concise 3-paragraph clinical summary for a \${drLabel} appointment. Patient uses continuous biometric monitoring (myDrSage V80 ring).

SPECIALIST CONTEXT: This report is for a \${drLabel}. \${specialistFocus}

PATIENT: ${p.age || '--'}yo ${p.sex || 'Unknown'} | Conditions: ${p.conditions || 'None'} | Health Grade: ${m.health_grade || 'B'}

7-DAY BIOMETRICS:
- HRV: ${c.hrv?.current || '--'}ms (age norm ${c.hrv?.age_norm || '--'}ms, trend: ${c.hrv?.trend?.label || '--'})
- RHR: ${c.rhr?.current || '--'} BPM (trend: ${c.rhr?.trend?.label || '--'})
- BP: ${c.bp?.systolic || '--'}/${c.bp?.diastolic || '--'} mmHg (${c.bp?.days_elevated || 0}/7 days elevated)
- SpO2: ${c.spo2?.current || '--'}%
- Sleep: ${s.total?.avg7d || '--'}h total, ${s.deep?.avg7d || '--'}h deep, ${s.rem?.avg7d || '--'}h REM
- Temp: ${t.last_night_f || '--'}°F (${t.deviation_f > 0 ? '+' : ''}${t.deviation_f || 0}°F from baseline)
- Steps: ${(a.steps_avg7d || 0).toLocaleString()}/day avg
- Readiness: ${m.recovery?.readiness || '--'}/100

${hasSignals ? `ACTIVE PATTERNS REQUIRING CLINICAL ATTENTION:
${activeSignals}

These are the specific patterns the patient wants to discuss at this visit. Focus your clinical narrative on these patterns and the biometric data that supports them.` : 'No active patterns flagged for this visit — general wellness review.'}

PATIENT COMMITMENTS: ${activeCommitments}

Write exactly 3 paragraphs:
1. Overall biometric picture this week — reference specific numbers
2. ${hasSignals ? 'Focus on the ACTIVE PATTERNS above — explain what the data shows and why it warrants clinical discussion. Be specific.' : 'General trends and anything worth noting clinically.'}
3. Specific questions the patient should raise with their physician at this visit — tailored to the active patterns

Clinical language. Specific numbers. No diagnosis. End with: "Data generated by myDrSage continuous biometric monitoring. For informational purposes only."\`;
}
